// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2dUPck2dezTGGUyUOtcK7ZG1QoW4zu0',
    appId: '1:599363620819:android:fc8ae7b1f83d4d6664a926',
    messagingSenderId: '599363620819',
    projectId: 'split-wise-891b7',
    storageBucket: 'split-wise-891b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbzavOs9_x-98uPTWvUJiI5ExBFjQkG5M',
    appId: '1:599363620819:ios:1271cf765f1603a264a926',
    messagingSenderId: '599363620819',
    projectId: 'split-wise-891b7',
    storageBucket: 'split-wise-891b7.firebasestorage.app',
    iosBundleId: 'com.example.splitWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbzavOs9_x-98uPTWvUJiI5ExBFjQkG5M',
    appId: '1:599363620819:ios:1271cf765f1603a264a926',
    messagingSenderId: '599363620819',
    projectId: 'split-wise-891b7',
    storageBucket: 'split-wise-891b7.firebasestorage.app',
    iosBundleId: 'com.example.splitWise',
  );
}
